### ISSUE TITLE
Generalization of const's type and value restriction

### ISSUE THREAD

**Issue by grayswandyr** [dbuenzli/fmt#39]
Hi,
I remarked some of my code breaks due to the generalization of `const`'s type as writing something such as:
```
let t = const string "t"
```
will yield a weak type variable in `t`'s type.
Granted, in the case of my code, I should anyway have created an interface to fix the type of my functions (and this is what I'm gonna do) but I thought you may be interested in this piece of information. I'm not sure what outcome you expect of generalizing `const`'s type compared to keeping `unit` in it?

**Comment by dbuenzli** [comment]
> I'm not sure what outcome you expect of generalizing `const`'s type compared to keeping `unit` in it?

Better compositionality with functions like [`append`](https://erratique.ch/software/fmt/doc/Fmt/index.html#val-append) (++), [`concat`](https://erratique.ch/software/fmt/doc/Fmt/index.html#val-concat), [`record`](https://erratique.ch/software/fmt/doc/Fmt/index.html#val-record). Previously we had the (now deprecated) `Fmt.{prefix,suffix}` which were a bit ad-hoc and not that convenient to use. For example the new `append` signature makes it easy to write things like: 

```ocaml
Fmt.(any "The int was " ++ int ++ any " but it wasn't in fact.") 
```
But for that to work you have to generalize constant printers (`Fmt.{const,any,comma,sp,...}` to accept arbitrary values (which they ignore) rather than just `unit`. 

The price to pay, as you noticed, is a bit of eta expansion if you name your constants.
