### ISSUE TITLE
Fmt.styled gets slower over time

### ISSUE THREAD

**Issue by talex5** [dbuenzli/fmt#52]
I've been investigating a problem with my programs slowing down over time, but only when logging is configured. The problem seems to be with fmt (0.8.10)!

With this test program:
```ocaml
let n = 10000

let () =
  while true do
    let t0 = Unix.gettimeofday () in
    for _i = 1 to n do
      ignore @@ Fmt.str "Hello %a" Fmt.(styled `Blue string) "world"
    done;
    let t1 = Unix.gettimeofday () in
    Printf.printf "Formatted %.0f messages/second\n%!" (float n /. (t1 -. t0))
  done
```
I get:
```
$ dune exec -- ./test.exe
Formatted 522518 messages/second
Formatted 411017 messages/second
Formatted 298257 messages/second
Formatted 215499 messages/second
Formatted 155861 messages/second
Formatted 110564 messages/second
Formatted 77171 messages/second
Formatted 54181 messages/second
Formatted 37493 messages/second
Formatted 25499 messages/second
Formatted 17254 messages/second
```
Replacing ``Fmt.(styled `Blue string)`` with `Fmt.string` shows no slow-down.

**Comment by dbuenzli** [comment]
Just tried to have a quick look at that. 

First my experience is a little bit different that yours. Performance actually goes up and down [1], likely with gc occurring.

The culprit is likely [this function](https://github.com/dbuenzli/fmt/blob/11221dcfd08c9b21c2dc63378fd6ffe75333fb33/src/fmt.ml#L615-L630). Each `Fmt.str` uses `Fmt.asprintf` which allocates a new ppf and that doesn't seem to match the expectations expressed in [this commit](https://github.com/dbuenzli/fmt/commit/cfc7caa62c5efe96e479a9d7a0e05455aa7ff5f6) (see the comment). 

Maybe we should [switch back](https://github.com/dbuenzli/fmt/commit/d200ffa4fae40168a5c68d4e8cf8c3a972af8d40) to the horrible hack we had before to store arbitrary metadata in the formatter itself by hijacking the tags mecanism.

[1]: 
Formatted 250658 messages/second
Formatted 223419 messages/second
Formatted 153010 messages/second
Formatted 121745 messages/second
Formatted 87265 messages/second
Formatted 240923 messages/second
Formatted 170360 messages/second
Formatted 137997 messages/second
Formatted 102244 messages/second
Formatted 100184 messages/second
Formatted 240310 messages/second
Formatted 170856 messages/second
Formatted 128041 messages/second
Formatted 92355 messages/second
Formatted 65714 messages/second
Formatted 77845 messages/second
Formatted 229642 messages/second

**Comment by talex5** [comment]
I was able to work around it by configuring my log reporter to use `Logs.pp_header` instead of `Logs_fmt.pp_header`. I admit I was a bit surprised to see ephemerons in the memtrace output while debugging this!

**Comment by dbuenzli** [comment]
> I was able to work around it by configuring my log reporter to use `Logs.pp_header` instead of `Logs_fmt.pp_header`.

Just to make things clear your log reporter eventually outputs using `Fmt.string` (or Format.asprintf) ?

**Comment by talex5** [comment]
My reporter uses `Fmt.kstr` and outputs with `output_string stderr` and/or to an in-memory ring-buffer:

https://github.com/talex5/wayland-proxy-virtwl/blob/22d4bca6170068f4a95a93114e48958d8cea54ae/trace.ml#L172

The use of `Logs_fmt` was left over from an older version (without a ring-buffer), and wasn't doing anything anyway.
